# Generated by Django 2.1 on 2019-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(blank=True, default='', null=True, upload_to='images')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='pictures',
            field=models.ManyToManyField(blank=True, to='events.Picture'),
        ),
    ]
