# Generated by Django 2.1 on 2018-11-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
