# Generated by Django 2.1 on 2018-10-21 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20181021_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='requisitos',
            new_name='requirements',
        ),
    ]
