# Generated by Django 2.1 on 2019-01-24 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0007_auto_20190122_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='positions_interested', to=settings.AUTH_USER_MODEL),
        ),
    ]
