# Generated by Django 2.1 on 2019-05-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='positions',
        ),
        migrations.AddField(
            model_name='position',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='projects.Project'),
            preserve_default=False,
        ),
    ]
