# Generated by Django 2.1 on 2019-07-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20190123_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
