# Generated by Django 2.1 on 2019-05-24 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='category.Category')),
                ('thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='images')),
            ],
            bases=('category.category',),
        ),
    ]
