# Generated by Django 2.1 on 2019-05-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincategory',
            name='category_ptr',
        ),
        migrations.AddField(
            model_name='maincategory',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='category.Category'),
            preserve_default=False,
        ),
    ]
