# Generated by Django 2.1 on 2018-10-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20181009_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.URLField(default='https://scontent.fntr3-1.fna.fbcdn.net/v/t1.0-9/42608173_2277643598915775_8315723684887134208_n.jpg?_nc_cat=100&_nc_ht=scontent.fntr3-1.fna&oh=3f78e092fbecd51302f9ceb7f02e5456&oe=5C4B74EB'),
            preserve_default=False,
        ),
    ]
