# Generated by Django 2.1 on 2018-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20181020_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('requisitos', models.CharField(max_length=255)),
                ('form', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='project', to='projects.Position'),
        ),
    ]
