# Generated by Django 2.1 on 2018-10-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20181021_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='compensation',
            field=models.CharField(default='compensado', max_length=255),
            preserve_default=False,
        ),
    ]
