# Generated by Django 2.1 on 2019-02-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='course',
            name='area',
        ),
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images'),
        ),
    ]
