# Generated by Django 2.1 on 2019-04-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190401_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.CharField(default='hello', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.CourseType'),
            preserve_default=False,
        ),
    ]
