# Generated by Django 2.1 on 2019-05-30 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190411_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverCarrousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CoverItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.AddField(
            model_name='covercarrousel',
            name='items',
            field=models.ManyToManyField(blank=True, to='courses.CoverItem'),
        ),
    ]
