# Generated by Django 2.1 on 2019-03-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_auto_20190103_0846'),
        ('organizations', '0003_auto_20190123_0355'),
        ('courses', '0003_auto_20190308_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('cover_image', models.ImageField(blank=True, default='', null=True, upload_to='images')),
                ('quick_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Organization')),
                ('categories', models.ManyToManyField(blank=True, related_name='events_event_related', to='category.Category')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Location')),
                ('tags', models.ManyToManyField(blank=True, related_name='events_event_related', to='category.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
